[package]
name = "mycelia"
version = "0.1.0"
edition = "2024"

[workspace]
members = [ "local-testing-server" ]

[dependencies]
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
bytes = "1"
