[package]
name = "local-testing-server"
version = "0.1.0"
edition = "2024"


[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
actix-files = "0.6.8"
actix-web = "4.11.0"
env_logger = "0.11.8"
log = "0.4.28"
